### ISSUE TITLE
Set python dependencies version in requirements.txt

### ISSUE THREAD

**Issue by dgarcia360** [srsran/srsRAN_4G_docs#17]
## Context

Sphinx docs depend on other tools and dependencies to build.  

The repository defines the dependencies in the `requirements.txt file`, but it does not specify which version of the packages should be installed. Therefore, when a third party dependency receives an update, there is the risk to break the local or production build if the latest update is not compatible. 

## Proposal

1. For each dependency, find the exact version number used in production.
2. List all the dependencies in the `requirements.txt file`. The file must list the exact version number for each dependency to make sure updates from third-party packages do not break the docs. For example:

```
# File: docs/requirements.txt

# Defining the exact version will make sure things don't break

sphinx==4.1.2
sphinx_rtd_theme==0.5.2
sphinxcontrib-seqdiag==2.0.0
sphinxcontrib-blockdiag==2.0.0
```

   3. Install the dependencies in a clean environment, and check the build does not break. 
   4. Test the changes on ReadTheDocs.

**Comment by brendan-mcauliffe** [comment]
Addressed in commit cb65968
