### ISSUE TITLE
Reuse conf.py in subprojects

### ISSUE THREAD

**Issue by dgarcia360** [srsran/srsRAN_4G_docs#19]
## Context

The repository contains several Sphinx subprojects.

Each subproject defines its own `conf.py`, but most settings are shared with the parent project. Instead, subprojects could inherit from the main project `conf.py`, and only overwrite the unique settings for the subproject.

By doing so, if you were to install new extensions or change a setting, you can make sure that the modification will be applied to all subprojects instead of having to update each conf.py file individually.

## Proposal

For every subproject:

1. In `conf.py`, extend from the main conf.py:

```python
import os
import sys
sys.path.insert(0, os.path.abspath('../../../..'))
 
from srsran_user_manuals.source.conf import *

```
2. Keep only the settings that are unique for the project, for example:

```
project = u'srsRAN Application Notes'
```

**Comment by brendan-mcauliffe** [comment]
Addressed in commits:  
dc28cb8
8cf1825
d14922a
