### ISSUE TITLE
Improve installation notes (README.md)

### ISSUE THREAD

**Issue by dgarcia360** [srsran/srsRAN_4G_docs#21]
## Context

The README explains how to install the Sphinx dependencies, but it does not specify which version.

## Proposal

Edit the README to guide the contributor on how to install the dependencies form the `requirements.txt` file. For example:

> On Ubuntu, they can be installed with:
> 
> ``` console
> sudo apt install python-pip
> pip install -r requirements.txt
> ```

**Comment by brendan-mcauliffe** [comment]
Addressed in commit d48ce1b
