### ISSUE TITLE
[PDF build] Fix table of contents

### ISSUE THREAD

**Issue by dgarcia360** [srsran/srsRAN_4G_docs#23]
## Context

The table of contents on the PDF version does not render correctly. It shows the following headings:

![image](https://user-images.githubusercontent.com/9107969/129598813-a3baf303-ecef-454e-8cdc-e2ce7a46d106.png)

Where it should render:

![image](https://user-images.githubusercontent.com/9107969/130275439-64782d10-74ab-4fec-a8ae-dd1f2dd265e7.png)

To render the left sidenav toctree instead, the index page should only have a single H1 title, some content, and the table of contents (without any other subheading).

## Proposal

There are two alternatives:

**A) Reorganize the index page (recommended)**

Edit the `index.rst` file:

1. Move  the context from **Index -> First Steps** under a new page **General > First Steps**.
2. Remove the heading **Links**.
3. In the toctree directive, set the option max_depth to 2. For example:

```
.. toctree::
   :maxdepth: 2
```

**B) Create a custom index page for PDF builds**

1. Create a second index page for PDF builds (e.g. `index_pdf.rst`, without any subheading). This index page should only have one H1 title, some content, and the table of contents (without any other subheading).

2. In ``conf.py``, change ``latex_documents`` option from:

```python
latex_documents = [
    (master_doc_pdf, 'srsRAN.tex', u'srsRAN Documentation',
     [author], 'manual'),
]
```
to:

```python
latex_documents = [
    ('index_pdf', 'srsRAN.tex', u'srsRAN Documentation',
     [author], 'manual'),
]
```

**Comment by brendan-mcauliffe** [comment]
Addressed in commit 375b14a
