### ISSUE TITLE
Add local documentation preview with livereload

### ISSUE THREAD

**Issue by dgarcia360** [srsran/srsRAN_4G_docs#24]
## Context

Every time a contributor changes the documentation in their local environment, they must run `sphinx-build -b html . _build` and open the `_build` directory to preview the changes.

The documentation toolchain can provide a command that starts a server at http://127.0.0.1:8000 and watches for changes in the docs local repository. When a change is detected, the documentation is rebuilt, and any open browser windows are reloaded automatically with the latest documentation contents.

## Proposal

Install the extension [sphinx-autobuild](https://github.com/executablebooks/sphinx-autobuild).

**Comment by brendan-mcauliffe** [comment]
Addressed in commit 5bd2bf6
