### ISSUE TITLE
Build previews for pull requests

### ISSUE THREAD

**Issue by dgarcia360** [srsran/srsRAN_4G_docs#27]
## Context

Merging pull request into `master` could break ReadTheDocs build.

There are two solutions to prevent this from happening:

### Option A: Build and publish a preview site for pull-requests (recommended)

RTD offers a [feature](https://docs.readthedocs.io/en/stable/pull-requests.html) to ensure the documentation build does not break before you merge a pull-request into the ``master`` branch. They also generate a preview site for each pull request.

⚠️This feature is available with [ReadTheDocs for Business](https://readthedocs.com/pricing/) Basic Plan.

To enable this feature:

1. Go to your project dashboard

2. Go to **Admin > Advanced settings**

3. Enable the **Build pull requests** for this project option

4. Click on **Save**.

### Option B: Build the docs in a GitHub Actions workflow

Create a [Github Actions workflow](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions) that builds the docs when:

- There is a new pull request targeting the master branch.
- The pull request receives a new commit. 

If the build fails or a warning is raised, the pull requests checks warn the user they should have to edit the pull request before merging it:

![image](https://user-images.githubusercontent.com/9107969/130270342-a8ac344c-5594-4ef5-b50a-337c3ef51a90.png)

**Comment by brendan-mcauliffe** [comment]
Builds are enabled for different public branches, and next is already enabled for automatic builds. Steps are already in place to ensure master doesn't break with new commits.
