### ISSUE TITLE
Add meta description to index page

### ISSUE THREAD

**Issue by dgarcia360** [srsran/srsRAN_4G_docs#28]
## Context

The current Google result for srsRAN_docs looks like:

![image](https://user-images.githubusercontent.com/9107969/130271885-759eb203-8dba-466f-aed3-858bace6eaf8.png)

From [Use meta tags](https://docs.readthedocs.io/en/stable/guides/technical-docs-seo-guide.html#use-meta-tags):

> Using a meta description allows you to customize how your pages look in search engine result pages.

> Typically search engines will use the first few sentences of a page if no meta description is provided. In Sphinx, you can customize your meta description using the following RestructuredText:

```
.. meta::
    :description lang=en:
        Adding additional CSS or JavaScript files to your Sphinx documentation
        can let you customize the look and feel of your docs or add additional functionality.
```

## Proposal

Add a custom meta description for the docs landing page in ``index.rst``. For example:

>  Documenation for the srsRAN project. Browse the latest developer documentation to build complete end-to-end mobile wireless networks.

**Comment by brendan-mcauliffe** [comment]
addressed in commit b819af2
