### ISSUE TITLE
Use a variable to render the docs version

### ISSUE THREAD

**Issue by dgarcia360** [srsran/srsRAN_4G_docs#29]
## Context

``index.rst`` harcodes the documentation version:

``` rst
srsRAN 21.04 Documentation
==========================
```
## Proposal

Instead,  use the directive ``|version|`` to update the documentation version number only on in one place (``conf.py`` > `version ` setting)  when this changes. For example:

``` rst
srsRAN |version| Documentation
==============================
```

**Comment by brendan-mcauliffe** [comment]
Addressed in commit b819af2
