### ISSUE TITLE
Update the copyright year automatically

### ISSUE THREAD

**Issue by dgarcia360** [srsran/srsRAN_4G_docs#30]
## Context

The file ``conf.py`` defines the copyright notice:

```python
copyright = u'2019-2021, Software Radio Systems'
```

Once a year, you have to submit a new PR to change the year.

### Proposal

Instead,  update the copyright year automatically with the following code snippet:

```python
from datetime import date
year = str(date.today().year)
copyright = '2019-' + year + ', Software Radio Systems.'
````

**Comment by brendan-mcauliffe** [comment]
Addressed in commit b819af2.
