### ISSUE TITLE
Minor correction in installation step

### ISSUE THREAD

**Issue by herlesupreeth** [srsran/srsRAN_4G_docs#8]
The documentation have the following step to install the configuration `sudo srslte_install_configs.sh user`, however I believe this has changed to `sudo srsran_install_configs.sh user`. srsRAN works flawlessly (tried VoLTE calls)..Amazing work

Thanks a lot

**Comment by suttonpd** [comment]
Thanks Supreeth! Fixed for 21.04 docs which have just been pushed to master.
